language: python

services:
  - docker
  

before_install:
  - docker build -t tsexton31/restapi .
  
  # Do what a docker compose file would

  - docker network create redisnet
  - docker ps
  - docker run -d --name redis --network redisnet redis
  - docker run -d -p 80:80 --network redisnet tsexton31/restapi
  #ensure ports are correct
  
script:
  - python websitetest.py
  
after_success:
  - docker login -u $D_USERNAME -p $D_PASSWORD
  - docker push tsexton31/restapi

